#!/usr/bin/env bash
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"

CONFIG=release
TARGET=chrome
JOBS=""
TARGET_CPU=""
GN_ONLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config) CONFIG="$2"; shift 2 ;;
    --target) TARGET="$2"; shift 2 ;;
    --jobs|-j) JOBS="$2"; shift 2 ;;
    --cpu) TARGET_CPU="$2"; shift 2 ;;
    --gn-only) GN_ONLY=1; shift ;;
    -h|--help)
      echo "usage: build.sh [--config release|debug] [--target chrome] [--cpu x64|arm64] [--jobs N] [--gn-only]"
      exit 0 ;;
    *) die "unknown argument: $1" ;;
  esac
done

case "$CONFIG" in release|debug) ;; *) die "config must be 'release' or 'debug'" ;; esac

use_depot_tools
require_checkout

OS="$(host_os)"
CPU="${TARGET_CPU:-$(host_cpu)}"
OUT_DIR="$OUT_ROOT/$CONFIG"

args_files=(
  "$REPO_ROOT/build/args/common.gni"
  "$REPO_ROOT/build/args/$OS.gni"
  "$REPO_ROOT/build/args/$CONFIG.gni"
)
[[ -f "$REPO_ROOT/build/args/local.gni" ]] && args_files+=("$REPO_ROOT/build/args/local.gni")

mkdir -p "$OUT_DIR"
{
  echo "# Generated by scripts/build.sh — edit build/args/*.gni instead."
  echo "target_cpu = \"$CPU\""
  for f in "${args_files[@]}"; do
    echo
    echo "# --- ${f#$REPO_ROOT/} ---"
    cat "$f"
  done
} > "$OUT_DIR/args.gn"

log "Configuring $CONFIG ($OS/$CPU)"
info "out: ${OUT_DIR#$REPO_ROOT/}"
(cd "$SRC_DIR" && gn gen "$OUT_DIR")

[[ "$GN_ONLY" == "1" ]] && exit 0

log "Building target '$TARGET'"
ninja_args=(-C "$OUT_DIR" "$TARGET")
[[ -n "$JOBS" ]] && ninja_args=(-j "$JOBS" "${ninja_args[@]}")
start=$SECONDS
(cd "$SRC_DIR" && autoninja "${ninja_args[@]}")
log "Built in $(( (SECONDS - start) / 60 ))m $(( (SECONDS - start) % 60 ))s"
info "next: make package CONFIG=$CONFIG"
